version: "3.8"

services:
  website:
    image: dachboden-session.de:website
    build:
      context: services/website
    volumes:
      - ./services/website/package.json:/app/package.json
      - ./services/website/src:/app/src
      - yarn-cache:/usr/local/share/.cache/yarn
    ports:
      - "3000:3000"

volumes:
  yarn-cache:
