version: "3.8"

services:
  website:
    container_name: dachboden-session-website
    working_dir: /app
    build:
      context: services/website
    ports:
      - "3000:3000"
    volumes:
      - ./services/website:/app
      - ./services/website/dist:/app/dist
    stdin_open: true
    tty: true
